In [1]:
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv(os.path.join("Resources", "Trump_Tweet_Data.csv"))

df = df.drop("Source", axis=1)

df.head()

Tweets  len  \
0  RT @WhiteHouse: In response to the virus, the ...  140   
1  RT @WhiteHouse: This Sunday, millions of Chris...  140   
2  RT @WhiteHouse: The data is clear: Our collect...  130   
3  RT @WhiteHouse: LIVE: Press Briefing with Coro...   88   
4                            https://t.co/HGD0GHUOjt   23   

                    ID                 Date  Likes    RTs  Market Movement  SA  
0  1248716255001030656  2020-04-10 20:55:29      0   5323                0   1  
1  1248716218867101696  2020-04-10 20:55:21      0   7271               -1  -1  
2  1248716207311773702  2020-04-10 20:55:18      0   4199                1   1  
3  1248670360507121665  2020-04-10 17:53:07      0   6191               -1   1  
4  1248653185969016833  2020-04-10 16:44:53  67151  18949               -1   0

In [3]:
target = df["Market Movement"]
target_names = ["Positive", "No Effect", "Negative"]

In [4]:
data = df.drop("Market Movement", axis=1)
feature_names = data.columns
data.head()

Tweets  len  \
0  RT @WhiteHouse: In response to the virus, the ...  140   
1  RT @WhiteHouse: This Sunday, millions of Chris...  140   
2  RT @WhiteHouse: The data is clear: Our collect...  130   
3  RT @WhiteHouse: LIVE: Press Briefing with Coro...   88   
4                            https://t.co/HGD0GHUOjt   23   

                    ID                 Date  Likes    RTs  SA  
0  1248716255001030656  2020-04-10 20:55:29      0   5323   1  
1  1248716218867101696  2020-04-10 20:55:21      0   7271  -1  
2  1248716207311773702  2020-04-10 20:55:18      0   4199   1  
3  1248670360507121665  2020-04-10 17:53:07      0   6191   1  
4  1248653185969016833  2020-04-10 16:44:53  67151  18949   0

In [5]:
# tokenize, then remove stopwords, ngrams, sentiment analysis feature selection
#either truncate or append to vector

In [21]:
from sklearn.feature_extraction.text import HashingVectorizer
# list of text documents
text = data["Tweets"]
# create the transform
vectorizer = HashingVectorizer(n_features=10000, ngram_range=(1, 3))
# encode document
vector = vectorizer.transform(text)
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

(200, 10000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
vector

<200x10000 sparse matrix of type '<class 'numpy.float64'>'
	with 9326 stored elements in Compressed Sparse Row format>

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(vector.toarray(), target, random_state=42)



In [24]:
from sklearn.svm import SVC 
model = SVC(kernel='linear')
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [25]:
print('Test Acc: %.4f' % model.score(X_test, y_test))

Test Acc: 0.3400


In [42]:
# Calculate classification report
from sklearn.metrics import classification_report
predictions = model.predict(X_test)
print(classification_report(y_test, predictions,
                            target_names=target_names))

              precision    recall  f1-score   support

    Positive       0.25      0.46      0.32        13
   No Effect       0.35      0.33      0.34        24
    Negative       0.33      0.08      0.12        13

    accuracy                           0.30        50
   macro avg       0.31      0.29      0.26        50
weighted avg       0.32      0.30      0.28        50



In [47]:
target = data["RTs"]
target_names = ["Positive", "No Effect", "Negative"]

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(vector.toarray(), target, random_state=42)

In [49]:
model = SVC(kernel='linear')
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [50]:
print('Test Acc: %.4f' % model.score(X_test, y_test))

Test Acc: 0.0200
